### ISSUE TITLE
[FEAT]Playback device Selection

### ISSUE THREAD

**Issue by steelgriffin1** [ultimategmbh/remote-volume#4]
I regularly check the volume and mute state of my Windows laptops to confirm that they are show-ready and it would make a huge difference if I was also able to check, change, or at least confirm which output device is currently active for playback. Windows has an annoying way of changing the output device at the worst possible time and seeing the status of the active device, the mute status, and the volume level, and being able to change these things remotely would be a huge benefit.

**Comment by ultimategmbh** [comment]
So at the moment changing the output device is not possible - but I found at least a way to show the current output device, so you could check that value and see if anything is not how its supposed to be.
